/**
 * heimdall — guardian extension for pi
 *
 * A single extension that provides multiple security guards:
 *   - secret-guard: blocks secret key references in bash, redacts values from output
 *   - command-policy-guard: enforces repo command policies from heimdall config
 *   - env-protect: blocks read tool calls targeting .env files
 *   - kubectl-secret-guard: blocks risky kubectl commands (get secrets, patch finalizers, exec)
 *   - sops-secret-guard: blocks sops decrypt invocations
 *   - sandbox-guard: native sandbox delegation via heimdall-sandbox (always-on)
 *
 * Config is loaded from three levels and deep-merged (later levels override earlier levels):
 *   - Generated defaults: ~/.pi/agent/heimdall.default.jsonc
 *   - User-level:        ~/.pi/agent/heimdall.jsonc (fallback: .json)
 *   - Project-level:     <cwd>/.pi/heimdall.jsonc (fallback: .json)
 *
 * sandbox-guard always runs (when enabled in config).
 * The following guards can be disabled via the `disabled` array:
 *   - secret-guard, command-policy-guard, env-protect,
 *   - kubectl-secret-guard, sops-secret-guard
 */

import { type ExtensionAPI, getAgentDir } from "@earendil-works/pi-coding-agent";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse, type ParseError } from "jsonc-parser";
import { DEFAULT_PRIVATE_PATHS } from "../guards/default-private-paths.js";
import type { HeimdallConfig } from "../guards/types.js";

import { registerSecretGuard } from "../guards/secret-guard.js";
import { registerCommandPolicyGuard } from "../guards/command-policy-guard.js";
import { registerEnvProtect } from "../guards/env-protect.js";
import { registerKubectlSecretGuard } from "../guards/kubectl-secret-guard.js";
import { registerSopsSecretGuard } from "../guards/sops-secret-guard.js";
import { registerSandboxGuard } from "../guards/sandbox-guard.js";

const OPT_OUT_GUARD_IDS = [
	"secret-guard",
	"command-policy-guard",
	"env-protect",
	"kubectl-secret-guard",
	"sops-secret-guard",
] as const;

const DEFAULT_CONFIG_BASENAME = "heimdall.default";
const USER_CONFIG_BASENAME = "heimdall";

/**
 * Deep merge: later levels override earlier levels. Objects merge recursively.
 * Arrays concatenate (overrides append to base).
 * Primitives and null from overrides win.
 */
export function deepMerge(base: HeimdallConfig, overrides: HeimdallConfig): HeimdallConfig {
	const result = { ...base };
	for (const key of Object.keys(overrides) as (keyof HeimdallConfig)[]) {
		const ov = overrides[key];
		if (ov === undefined) continue;
		const bv = base[key];
		if (
			typeof ov === "object" && ov !== null && !Array.isArray(ov) &&
			typeof bv === "object" && bv !== null && !Array.isArray(bv)
		) {
			(result as Record<string, unknown>)[key] = deepMerge(
				bv as HeimdallConfig,
				ov as HeimdallConfig,
			);
		} else if (Array.isArray(ov) && Array.isArray(bv)) {
			(result as Record<string, unknown>)[key] = [...bv, ...ov];
		} else {
			(result as Record<string, unknown>)[key] = ov;
		}
	}
	return result;
}

export function parseConfig(raw: string): HeimdallConfig | null {
	try {
		const errors: ParseError[] = [];
		const parsed = parse(raw, errors, { allowTrailingComma: true });
		if (errors.length === 0 && parsed && typeof parsed === "object") return parsed;
	} catch {
		// Parse error — skip
	}
	return null;
}

function preferredConfigPath(dir: string, basename: string): string | undefined {
	const jsoncPath = join(dir, `${basename}.jsonc`);
	if (existsSync(jsoncPath)) return jsoncPath;
	const jsonPath = join(dir, `${basename}.json`);
	if (existsSync(jsonPath)) return jsonPath;
	return undefined;
}

export function loadConfigFile(path: string | undefined): HeimdallConfig | null {
	if (!path || !existsSync(path)) return null;
	return parseConfig(readFileSync(path, "utf-8"));
}

export function defaultConfigText(): string {
	const denyList = DEFAULT_PRIVATE_PATHS.map((path) => `\t\t\t\t${JSON.stringify(path)}`).join(",\n");
	return `// Generated by pi-heimdall for transparency.\n// This file may be overwritten when Heimdall starts.\n// Put local changes in heimdall.jsonc or a project .pi/heimdall.jsonc file.\n{\n\t"sandbox": {\n\t\t"enabled": false,\n\t\t"useDefaultFilesystemDeny": true,\n\t\t"filesystem": {\n\t\t\t"deny": [\n${denyList}\n\t\t\t],\n\t\t\t"writable": [\n\t\t\t\t"~/.pi"\n\t\t\t]\n\t\t}\n\t}\n}\n`;
}

function generatedDefaultConfigPath(agentDir: string): string {
	return join(agentDir, `${DEFAULT_CONFIG_BASENAME}.jsonc`);
}

function ensureGeneratedDefaultConfig(agentDir: string): string {
	mkdirSync(agentDir, { recursive: true });
	const defaultPath = generatedDefaultConfigPath(agentDir);
	writeFileSync(defaultPath, defaultConfigText());
	return defaultPath;
}

function withoutGeneratedDeny(config: HeimdallConfig): HeimdallConfig {
	return {
		...config,
		sandbox: {
			...config.sandbox,
			filesystem: {
				...config.sandbox?.filesystem,
				deny: [],
			},
		},
	};
}

export function mergeConfigLevels(defaultConfig: HeimdallConfig | null, userConfig: HeimdallConfig | null, projectConfig: HeimdallConfig | null): HeimdallConfig {
	let merged = deepMerge(defaultConfig ?? {}, userConfig ?? {});
	merged = deepMerge(merged, projectConfig ?? {});

	if (merged.sandbox?.useDefaultFilesystemDeny === false && defaultConfig) {
		merged = deepMerge(withoutGeneratedDeny(defaultConfig), userConfig ?? {});
		merged = deepMerge(merged, projectConfig ?? {});
	}

	return merged;
}

export function loadEffectiveConfig(agentDir: string, cwd: string): { config: HeimdallConfig; defaultConfigPath: string; projectConfigPath: string | undefined } {
	const defaultConfigPath = ensureGeneratedDefaultConfig(agentDir);
	const userConfigPath = preferredConfigPath(agentDir, USER_CONFIG_BASENAME);
	const projectConfigPath = preferredConfigPath(join(cwd, ".pi"), USER_CONFIG_BASENAME);

	const defaultConfig = loadConfigFile(defaultConfigPath);
	const userConfig = loadConfigFile(userConfigPath);
	const projectConfig = loadConfigFile(projectConfigPath);

	return {
		config: mergeConfigLevels(defaultConfig, userConfig, projectConfig),
		defaultConfigPath,
		projectConfigPath,
	};
}

export default function heimdall(pi: ExtensionAPI) {
	// Keep generated defaults current as soon as the extension is loaded, not only
	// after a chat session starts. This matters for source installs because
	// `pi install /path/to/pi-heimdall` only registers the package; users still
	// expect the visible default config to appear on the next Pi startup.
	ensureGeneratedDefaultConfig(getAgentDir());

	let config: HeimdallConfig = {};
	let projectConfigPath: string | undefined;
	const disabledSet = new Set<string>();

	pi.on("session_start", async (_event, ctx) => {
		config = {};
		disabledSet.clear();
		const effective = loadEffectiveConfig(getAgentDir(), ctx.cwd);
		config = effective.config;
		projectConfigPath = effective.projectConfigPath;

		if (Array.isArray(config.disabled)) {
			for (const d of config.disabled) {
				disabledSet.add(d);
			}
		}

		const disabledCount = [...disabledSet].filter((d) => OPT_OUT_GUARD_IDS.includes(d as typeof OPT_OUT_GUARD_IDS[number])).length;
		const active = OPT_OUT_GUARD_IDS.length - disabledCount + 1; // +1 for sandbox-guard
		const disabled = disabledCount > 0
			? ` (disabled: ${[...disabledSet].filter((d) => OPT_OUT_GUARD_IDS.includes(d as typeof OPT_OUT_GUARD_IDS[number])).join(", ")})`
			: "";
		ctx.ui.notify(`heimdall: ${active} guards active${disabled}; defaults: ${effective.defaultConfigPath}`, "info");
	});

	// Always registered, but runtime behavior follows current loaded config.
	registerSandboxGuard(pi, () => config, () => projectConfigPath);

	// Opt-out guards
	registerSecretGuard(pi, disabledSet);
	registerCommandPolicyGuard(pi, () => config, disabledSet);
	registerEnvProtect(pi, disabledSet);
	registerKubectlSecretGuard(pi, disabledSet);
	registerSopsSecretGuard(pi, disabledSet);
}
